const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
const CURRENCIES_FETCH = 'CURRENCIES_FETCH';
const EXPENSES_SUBMIT = 'EXPENSES_SUBMIT';
const DELETE_SUBMIT = 'DELETE_SUBMIT';
const ENABLE_FORM_TO_EDIT = 'ENABLE_FORM_TO_EDIT';
const EDIT_SUBMIT = 'EDIT_SUBMIT';

export {
  LOGIN_SUBMIT,
  CURRENCIES_FETCH,
  EXPENSES_SUBMIT,
  DELETE_SUBMIT,
  ENABLE_FORM_TO_EDIT,
  EDIT_SUBMIT,
};
